# Generated by Django 3.0.6 on 2021-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to='img\\%y'),
            preserve_default=False,
        ),
    ]
