# Generated by Django 3.0.6 on 2021-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0002_auto_20210205_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[(1, 'war'), (1, 'politics'), (2, 'politics'), (3, 'Environment'), (3, 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
