# Generated by Django 3.0.6 on 2021-01-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0003_auto_20210128_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
