# Generated by Django 3.0.6 on 2021-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0004_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
