# Generated by Django 3.0.6 on 2021-04-02 17:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0006_remove_product_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='img/')),
                ('tags', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=200)),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
