# Generated by Django 3.0.6 on 2021-04-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmin', '0007_auto_20210402_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_upload',
            name='country',
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='countries',
            field=models.CharField(max_length=1000),
        ),
    ]
